---
driver:
  name: azurerm

driver_config:
  subscription_id: '829eeca2-0445-402d-bf81-4d00f1093c64'
  location: 'West US'
  machine_size: 'Standard_D1'

provisioner:
  name: chef_zero

transport:
  ssh_key: ~/.ssh/id_kitchen-azurerm

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
    driver_config:
      image_urn: Canonical:UbuntuServer:16.04-LTS:latest
      vm_name: azurex2
      vm_tags:
        ostype: linux
        distro: ubuntu

suites:
  - name: default
    run_list:
      - recipe[azurex2::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
